theme: jekyll-theme-minimal
title: 'ESG ETfs: Is it possible to find financial strength whilst being socially responsibl?'
description: A deep dive into how ESG funds behave in comparision to the rest of the market.
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
